#ifndef ERRORS_H
#define ERRORS_H

#include <stdexcept>
#include <string>

// These are the errors thrown by the Database.
// Do not edit this file.

class DuplicateReport: public std::runtime_error {
  unsigned int report_id;
public:
  DuplicateReport(unsigned int id): std::runtime_error("Duplicate report: " + std::to_string(id))  {
    report_id = id;
  }
};

class NoSuchReport: public std::runtime_error {
  unsigned int report_id;
public:
  NoSuchReport(unsigned int id): std::runtime_error("No such report: " + std::to_string(id)) {
    report_id = id;
  }
};

#endif
