#ifndef REPORT_H
#define REPORT_H

// This is the structure used to represent police reports.
// Do not edit this file.

struct Range {
  float min;
  float max;
};

struct Report {
  unsigned int id;

  Range age;
  Range height;
  Range weight;
};

#endif
